### PR TITLE
refactor(identity): button and input styling

### PR DESCRIPTION
**Pull request by seaerchin**
## Problem
Some styling in #559 does not adhere to isomer styling and hence looked awkward. This PR made minor stylistic fixes to those portions 

## Solution
1. add padding on input to avoid congestion
2. use isomer button styling

## Before & After Screenshots

**BEFORE**:

image

**AFTER**:

image

### CODE REVIEW

**Review by NatMaeTan — APPROVED** [review]

**Comment by NatMaeTan** [comment]
Do you need a button for people to read more about this change? In case they still missed the banner?

And do you need to clarify that they cannot proceed to editing without verifying their email?

**Comment by seaerchin** [comment]
> Do you need a button for people to read more about this change? In case they still missed the banner?
> 
> And do you need to clarify that they cannot proceed to editing without verifying their email?

from offline discussion, will update to "In order to improve security, a verified email is now required for all users of IsomerCMS. Only .[gov.sg](http://gov.sg/) or **whitelisted email addresses** will be accepted. You must verify your email before proceeding. Read more"

**Comment by seaerchin** [comment]
@NatMaeTan updated to the below! 
image

**Comment by NatMaeTan** [comment]
Can ".gov.sg or" also be **bolded** haha sorry

**Review by NatMaeTan — APPROVED** [review]

**Review by alexanderleegs — APPROVED** [review]
lgtm!

**Pull request merged**
