### PR TITLE
release(0.28.0): merge to prod

### PR DESCRIPTION
**Pull request by seaerchin**
## What's Changed
* Release 0.27.0 to develop by @kishore03109 in https://github.com/isomerpages/isomercms-frontend/pull/1276
* fix(workspace): update feature tour hierarchy by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1278 verified by @kishore03109 
* fix(resourceCategorySpec): fix e2e tests by @kishore03109 in https://github.com/isomerpages/isomercms-frontend/pull/1270 verified by @kishore03109 
* fix: file name in test by @alexanderleegs in https://github.com/isomerpages/isomercms-frontend/pull/1280 verified by @kishore03109 
* build(netlify): add plugin for netlify to inject app version by @seaerchin in  https://github.com/isomerpages/isomercms-frontend/pull/1274  verified by @kishore03109 
* build(dd): add source maps for frontend  by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1279  verified by @kishore03109 
* feat(requestoverview): add link to staging/cms by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1161  verified by @kishore03109 

**Full Changelog**: https://github.com/isomerpages/isomercms-frontend/compare/v0.27.0...v0.28.0

**Deploy notes**
- [x] remove the `REACT_APP_VERSION` env var from netlify (done for staging) since that is extra.
- [x] change the command for `prod` to `npm run build:netlify`
- [x] change the command for `staging` to `npm run build:netlify`

### CODE REVIEW

**Comment by seaerchin** [comment]
Tests for #1278 

- [ ] clear the localStorage of the feature tour key
- [ ] go to a site w/ a review request pending on email login
- [ ] navigate to the dashboard
- [ ] ensure that the feature tour still works
- [ ] go to the workspace
- [ ] check that the components are visually consistent

**Comment by seaerchin** [comment]
Tests for #1274 

**Tests**
- [ ] go to `staging` 
- [ ] click on something **(ensure no blocking of requests)**
- [ ] go to dd dashboard
- [ ] version should be updated

**Comment by seaerchin** [comment]
Tests for #1279 
the site needs to be deployed first prior to running the below tets
- [ ] navigate to the `staging` site 
- [ ] sign out if required
- [ ] change the url to `/sites/e2e-test-repo/workspace`
- [ ] go to datadog and search for your session (this is hard atm ._. but we can filter by time to post deploy)
- [ ] observe that a 401 error has been thrown
- [ ] click on it 
- [ ] the error stack section on dd should have a detailed trace w filename insetad of `<nonsense>.chunk.js`

**Comment by seaerchin** [comment]
Tests for #1161 

- [ ] navigate to a email login based repo
- [ ] create a new image
- [ ] create a new file
- [ ] create a new unlinked page
- [ ] create a new page in folder
- [ ] create a new page in a subfolder
- [ ] create a new resource room page 
- [ ] repeat the above steps but edit existing items rather than creating
- [ ] create a new **empty** folder + subcollection
- [ ] create a new **empty** collection + sub collection
- [ ] delete an item 
- [ ] move an item
- [ ] request a review
- [ ] pages should be able to have a staging + cms link, files/images should not
- [ ] the deleted item should not show up
- [ ] the moved item should show only as a new item

**Comment by seaerchin** [comment]
e2e failures verified by @seaerchin - ran on `localhost` w/ release branches to minimise flakes.

**Review by kishore03109 — APPROVED** [review]

**Pull request merged**
