### PR TITLE
Fix/misc UI fixes

### PR DESCRIPTION
**Pull request by alexanderleegs**
This PR fixes a range of UI issues brought up in the recent [UX review](https://docs.google.com/document/d/1_aC5FuHqSQqqWx0aOcpDFyw2iEk1vsCpDgt4fLQ1zck/edit#bookmark=id.tae0sux04cgu).

The changes made in this PR are:
- **Top Nav Bar**
  - [Copy changes] Modal copy: Second sentence can change to ‘Refresh your staging site to see if your changes have been built’
- **Side Nav Bar**
  - The Settings tab sets the sitename first, so there is no more jumping of the sidebar when moving to settings.
  - The external link icons have been removed from Guide and Help
  - The hover state for the logged in as tab has been removed
- **Images/Files Modal**
  - [Copy changes] Modal title (it’s important for the title to reflect the intent of the task)
    - When user is uploading a new image, modal title should say ‘Upload new image’
    - When user is editing file name, modal title should say ‘Edit image details’
  - [Copy changes] At ‘Edit image details’ modal, change the button name ‘Upload’ to ‘Save’. It should be disabled first, only when the filename is changed, ‘Save’ button becomes blue.
- **EditPage Upload Image Modal**
  - Fixed bug preventing upload of images
- **EditNavBar**
  - Header: Spell out ‘Nav Bar’ to ‘Navigation Bar’
  - Replace `Links` with `Menu` and `Sublinks` with `Submenu`
    - Title: ‘Links’ should be called ‘Menu’.
    - Remove ‘Sublinks’ in the card title ‘Sublinks: Start Business’. Menu cards should just show the Menu titles aka ‘Start Business’ 
    - Title: ‘Sublinks’ should be ‘Submenu’
    - Input text field: ‘Nav title’ should be ‘Menu title’
    - Input text field: ‘Sublink title’ should be ‘Submenu title’
    - Button: ‘Delete link’ change to ‘Delete Menu’
    - Button: ‘Delete sublink’ change to ‘Delete Submenu’
  - Tighten the spacing between the cards

### CODE REVIEW

**Review by gweiying — CHANGES_REQUESTED** [review]
Changes look good, some suggestions:


**Side Nav Bar**
> The Settings tab sets the sitename first, so there is no more jumping of the sidebar when moving to settings.

Can we set site url on Settings tab as well?

**Images/Files Modal**
> [Copy changes] At ‘Edit image details’ modal, change the button name ‘Upload’ to ‘Save’. It should be disabled first, only when the filename is changed, ‘Save’ button becomes blue.

Delete button takes a while to become enabled?
Update: As discussed offline, we will wait for design input to resolve this issue. 

**EditNavBar**

> - Replace Links with Menu and Sublinks with Submenu
>   - Title: ‘Links’ should be called ‘Menu’.
>   - Remove ‘Sublinks’ in the card title ‘Sublinks: Start Business’. Menu cards should just show the Menu titles aka ‘Start Business’
>   - Title: ‘Sublinks’ should be ‘Submenu’
>   - Input text field: ‘Nav title’ should be ‘Menu title’
>   - Input text field: ‘Sublink title’ should be ‘Submenu title’
>   - Button: ‘Delete link’ change to ‘Delete Menu’
>   - Button: ‘Delete sublink’ change to ‘Delete Submenu’

Initialised value should be changed to "Menu title" and "Submenu title"? See below
Screenshot 2021-04-15 at 10 04 18 AM

**Comment by gweiying** [comment]
A related issue to the Delete button on the Image modal is that if there's a validation error for the image name, the Delete button should not be deactivated.

**Comment by alexanderleegs** [comment]
> **Side Nav Bar**
> 
> Can we set site url on Settings tab as well?

Resolved in https://github.com/isomerpages/isomercms-frontend/pull/409/commits/ca5ea574d18db24cac89545d25b49853838846df

> **Images/Files Modal**
> 
> Delete button takes a while to become enabled?
> Update: As discussed offline, we will wait for design input to resolve this issue.

Resolved in https://github.com/isomerpages/isomercms-frontend/pull/409/commits/22df073c45a2437d3710502bdfde87326c99e9d5 - we will use a loading spinner

> **EditNavBar**
> 
> Initialised value should be changed to "Menu title" and "Submenu title"? See below
> Screenshot 2021-04-15 at 10 04 18 AM

Resolved in https://github.com/isomerpages/isomercms-frontend/pull/409/commits/c0547b13a9ed26967ec173ace895d50e91480e81

>A related issue to the Delete button on the Image modal is that if there's a validation error for the image name, the Delete button is deactivated, which it should not be.

Resolved in https://github.com/isomerpages/isomercms-frontend/pull/409/commits/93f20c11654c1018aad7774dfa191291f382cecf

**Review by gweiying — APPROVED** [review]
lgtm

**Pull request merged**
