### PR TITLE
release(v0.63.0): merge to production

### PR DESCRIPTION
**Pull request by seaerchin**
## What's Changed
* 0.62.0 to develop by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1710
* feat(tiptap): allow inserting of complex blocks by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1697
* feat(tiptap): add card grid block by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1701
* feat(cards): introduce drawer to support sub-editing by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1704
* feat(cards): allow editing of cards within drawer by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1705
* feat(cards): support undo/redo of cards editing by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1706
* feat(cards): render preview the same way as template by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1707
* feat(editor): add trailing node at end of document by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1716
* fix(editor): improve embed functionality by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1717
* fix(markdowneditpage): fix styling on big screens by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1719
* Feat/select media modal for external media by @alexanderleegs in https://github.com/isomerpages/isomercms-frontend/pull/1714
* feat: basic accordion block by @kishore03109 in https://github.com/isomerpages/isomercms-frontend/pull/1709
* feat_background_toggling by @kishore03109 in https://github.com/isomerpages/isomercms-frontend/pull/1713
* feat(tiptap): add outline blocks  by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1718
* refactor(tiptap): add placeholder instead of prefill by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1724
* refactor(tiptap): change embeds view by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1723
* fix(tables): update table behaviour by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1722
* feat(editor): feature flag complex blocks by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1720
* feat(editor): enhance image bubble menu with more functions by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1721
* chore: swap preview fonts by @alexanderleegs in https://github.com/isomerpages/isomercms-frontend/pull/1715

**Full Changelog**: https://github.com/isomerpages/isomercms-frontend/compare/v0.62.0...v0.63.0

### CODE REVIEW

**Comment by seaerchin** [comment]
wtf alot of changes sia

**Comment by seaerchin** [comment]
@seaerchin #1697

**cards**
@seaerchin #1701 (no tests) 
@seaerchin #1704 (no tests)
@seaerchin #1705 (no tests)
@seaerchin #1706 (no tests)
@seaerchin #1707 (no tests)

**accordion**
@seaerchin #1709 (no tests)
@seaerchin #1713 (no tests)

@seaerchin #1716 
@seaerchin #1717 
@kishore03109  #1719 (adding rn monkas) 
@seaerchin #1714
@kishore03109 #1718 (adding rn monkas) 
@kishore03109 #1724 (adding rn monkas)
@kishore03109 #1723 (adding rn monkas) 
@kishore03109 #1722 (adding rn monkas) 
@seaerchin #1721 (adding rn monkas) 
@kishore03109 #1720 (adding rn monkas)

**reverting #1715**

**Comment by kishore03109** [comment]
for #1749
is this a concern? 
Screenshot 2023-12-05 at 6 22 08 PM

**Comment by kishore03109** [comment]
@kishore03109  #1719 (adding rn monkas) 
@seaerchin #1714
@kishore03109 #1718 (adding rn monkas) 
@kishore03109 #1724 (adding rn monkas) [done]
@kishore03109 #1723 (adding rn monkas) 
@kishore03109 #1722 (adding rn monkas) 
@seaerchin #1721 (adding rn monkas) 
@kishore03109 #1720 (adding rn monkas)

**Comment by kishore03109** [comment]
Current issues 

Backspace on table + embed gives weird output
https://github.com/isomerpages/isomercms-frontend/assets/42832651/7931bd22-86ca-4b42-a121-9f8dbe4df6e0

Adding image to a newly created page throws an error 
https://github.com/isomerpages/isomercms-frontend/assets/42832651/906d344e-91a8-40df-aacd-cedbb0a31090

**Comment by seaerchin** [comment]
@kishore03109 thanks for catching

the embed issues are specifically _formsg_ embeds specific because we (in the form of tiptap extensions) differentiate between iframe/insta/formsg embeds.

i tested w/ all 3 for the backspace + the embed menu -> no issue

the insert image one is fixed with slightly wonk semantics, as follows:
1. if there's a selection (user highlights) - we insert after the ending range of the selection.
2. if there's **no** selection **and line empty**: retain empty line, insert after (dedicated 15 mins, couldn't find a good enough solution. technically deducting 1 works but then idk how to check if line's empty)
3. if there's **no** selection **and line has content**: insert at cursor position.

**Review by kishore03109 — APPROVED** [review]

**Pull request merged**
