### PR TITLE
feat: introduce new version of NotFoundPage

### PR DESCRIPTION
**Pull request by dcshzj**
## Problem

The current NotFound page is outdated and the design is different from what we [currently have on Figma](https://www.figma.com/file/7OtNYkc4s9BkFk05ConEbd/%E2%AD%90-V1.5?type=design&node-id=1547-66213).

This PR was also made to get familiar with the frontend codebase.

## Solution

**Breaking Changes**

- [ ] Yes - this PR contains breaking changes
- [x] No - this PR is backwards compatible

**Features**:

- A new NotFound page is introduced to replace the existing one, and is updated to conform to the newer aspects of our codebase.

**Bug Fixes**:

- The "Back to dashboard" link previously did not work as intended when the user gets a NotFound error within their site, as the `siteName` parameter would not be present when the NotFound page is loaded (since it is loaded under a different route). This PR fixes this issue.

## Before & After Screenshots

**BEFORE**:

Screenshot 2023-08-23 at 11 36 36 AM

**AFTER**:

Screenshot 2023-08-23 at 11 36 55 AM

## Tests

- [ ] Unit tests (using `npm run tests`)
- [ ] e2e tests (comment on this PR with the text `!run e2e`)
- [x] Smoke tests
    - Navigate to a random non-existent page outside of a site (i.e. `/not/found`), the "Back to dashboard" button should link you to `/sites`.
    - Navigate to a random non-existent page within a site (i.e. `/sites/zhongjun-test/notfound`), the "Back to dashboard button should link you to `/sites/zhongjun-test`.

## Deploy Notes

*None*

### CODE REVIEW

**Review by seaerchin — APPROVED** [review]
Lgtm for this.

One question that needs to be asked is do we know why users end up seeing this page? I think it's easy to dismiss out of hand as the users entering an invalid site but there might be valid issues at play.

Something that could help here (in follow up PR also can) is just to have a button or something that they can use to submit a bug report **whilst also attaching the RUM replay I'd**

**Comment by dcshzj** [comment]
@seaerchin For now this is a generic catch-all page, but I agree we should be able to include some tracking mechanism here to record the previous route that the user was on, so that it facilitates our debugging.

I'll defer the design part to @sehyunidaaa since technically this PR is not part of any existing tasks, and she can look into this in greater detail when she has the time.

@sehyunidaaa Pending your design review, thanks!

**Comment by kishore03109** [comment]
@dcshzj fyi chromatic comment not working yet :(, you can trigger it directly via cli

**Review by kishore03109 — APPROVED** [review]

**Comment by dcshzj** [comment]
!run-chromatic

**Comment by dcshzj** [comment]
!run-chromatic

**Review by QiluXie — APPROVED** [review]
lgtm

**Comment by dcshzj** [comment]
!run-chromatic

**Comment by sehyunidaaa** [comment]
Reviewed, accepted [on chromatic](https://www.chromatic.com/test?appId=61fcc8e14c3af9003a102ac9&id=64e5cfd4bf336c9a4ebbaed5)

**Pull request merged**
