### PR TITLE
release(v0.51.0): merge to prod

### PR DESCRIPTION
**Pull request by seaerchin**
⚠️ Remove the styles feature flag on GB after deployment ⚠️
## What's Changed
* chore(styles): remove styles feature flagging for special pages by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1579
* 0.50.0 (dev) by @alexanderleegs in https://github.com/isomerpages/isomercms-frontend/pull/1576
* refactor(editpage): abstract out overwrite changes warning modal by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1577
* Fix/allow user edits for open review request by @alexanderleegs in https://github.com/isomerpages/isomercms-frontend/pull/1587
* refactor(media): paginate images by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1578
* ref(media): update media hooks + components by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1581
* feat(homepage): allow user to override changes when there is a conflict by @dcshzj in https://github.com/isomerpages/isomercms-frontend/pull/1588
* chore(hooks): remove `useGetMediaFolders` by @seaerchin in https://github.com/isomerpages/isomercms-frontend/pull/1582

**Full Changelog**: https://github.com/isomerpages/isomercms-frontend/compare/v0.50.0...v0.51.0

### CODE REVIEW

**Review by dcshzj — APPROVED** [review]

**Comment by seaerchin** [comment]
#1578 

- [ ] Go to any repo (preferably a-test-v4 or nlb)
- [ ] click on the images
- [ ] if there are >15 images, there should be a pagination component
- [ ] clicking on a diff page should refetch 
- [ ] **clicking on a page that was previously rendered should not trigger a refetch**
- [ ] uploading the image should proceed normally
- [ ] clicking on an image should proceed normally (+ show preview)
- [ ] go to a content page
- [ ] selecting an image to insert/uplodaing image shuold proceed normally
- [ ] repeat the above for files

**Comment by seaerchin** [comment]
#1581 

## Tests
- [ ] go into `a-test-v4` repo
- [ ] upload an image
- [ ] UI should re-render to display new image
- [ ] rename image
- [ ] UI should re-render to display new name (only 1 item should re-render) 
- [ ] delete an image 
- [ ] UI should re-render to remove item 
- [ ] move the image into a subdirectory
- [ ] UI should re-render to remove item
- [ ] subdirectory should have item
- [ ] repeat teh above steps but on a sub-directory (ie, try to perform CRUD operations on a sub-directory)

**Comment by seaerchin** [comment]
#1588 
    - [ ] Navigate to any site and open 2 tabs of the Homepage editor
    - [ ] Make a valid change on the first tab and save. Verify that the changes can be saved successfully.
    - [ ] Switch to the second tab and make another change that is not the same as the first one.
    - [ ] Save the changes. Verify that the override modal (screenshot above) appears, and there is no error toast shown behind the warning modal.
    - [ ] Click on "Save my edits anyway", verify that the second set of changes have been saved successfully.

**Review by alexanderleegs — COMMENTED** [review]
#1587 

- [ ] User edits for open review request
  - [x] Log in via email
  - [x] Check that pages can be be edited with no review request and create review request button in header is clickable
  - [x] Create a RR
  - [ ] Check that pages can be edited but create review request button in header is not clickable
  - [ ] Approve RR
  - [ ] Check that pages cannot be edited, and you get redirected back to dashboard (and create review request button in header is not clickable)

**Comment by seaerchin** [comment]
#1579 
  - [ ] Navigate to any site
  - [ ] Verify that the EditHomepage page shows the new styles
  - [ ] Verify that the EditNavbar page shows the new styles
  - [ ] Verify that the EditContactUs page shows the new styles

⚠️ Remove the styles feature flag on Growthbook after deployment ⚠️

**Comment by seaerchin** [comment]
#1577

- [ ] Go to any site
    - [ ] Open the page editor for a single page on two tabs (both tabs editing the same page)
    - [ ] Make changes and save on the first tab, ensure that the page has saved successfully
    - [ ] Make changes on the second tab and save, verify that the override changes warning modal appears as intended
    - [ ] Click on Override, verify that the changes are indeed overwritten on the repository

**Pull request merged**
