### PR TITLE
release(0.41.0): merge to `prod` 

### PR DESCRIPTION
**Pull request by seaerchin**
dup of #1463

# Env vars
~REACT_APP_GROWTHBOOK_CLIENT_KEY : this is required for GrowthBook SDK to connect with the cloud~

### CODE REVIEW

**Comment by seaerchin** [comment]
#1435 @seaerchin 
- [ ] Navigate to a random non-existent page outside of a site (i.e. /not/found), the "Back to dashboard" button should link you to /sites.
- [ ] Navigate to a random non-existent page within a site (i.e. /sites/zhongjun-test/notfound), the "Back to dashboard button should link you to /sites/zhongjun-test.

**Comment by seaerchin** [comment]
#1449 @seaerchin 
Part 1 - Basic Usage

- [ ] Create a feature flag on GrowthBook - either boolean or string or object
- [ ] Use `useGrowthBook` hook to get the GB instance
- [ ] Use the `useFeatureIsOn` or `useFeatureValue` hooks to retrieve the created flag
- [ ] Perform a conditional render inside one of our pages (e.g. render Hello if flag is true, else render World)

Part 2 - Attribute Setting

- [ ] Pick an attribute of your account to test, e.g. userId
- [ ] Ensure this exists on GrowthBook control panel, else add it
- [ ] Select a feature flag to test experimenting
- [ ] Modify the feature flag, under Dev environment, to use a forced value
- [ ] Enable a unique value specific to your chosen attribute
- [ ] Perform a conditional render similar to part 1. This should work
- [ ] Remove the forced value option and re-test to ensure you get the default value

**Comment by seaerchin** [comment]
#1458 @harishv7 
    - [ ] Navigate to Contact Us page for a site that has this new stylings enabled (defined in `OGP_SITES` and `TESTING_SITES`)
    - [ ] Add new location section and contact information section. This should work as intended.
    - [ ] Edit the fields in existing and new sections, the preview should update and validation feedback should appear immediately.
    - [ ] Delete a card in the location section and contact information section.
    - [ ] Add cards in the operating hours section of any location.
    - [ ] Edit the fields in the operating hours card.
    - [ ] Delete an operating hours card.
    - [ ] Drag and drop for first level (locations and contact information), and for second level (operating hours in location) should work as intended.
    - [ ] Save changes to the contact us page. The staging site should build in a way that is similar to how the preview looks.

**Comment by seaerchin** [comment]
#1457 @seaerchin 
- [ ] Go to edit nav bar
- [ ] Add sections, all of them should work
- [ ] Type in the section fields, preview should update
  - [ ] Changing the folder in a folder section should change all the related sublinks
- [ ] Drag and drop should work (first level)
- [ ] Deleting a section should work
- [ ] Type in a very long string for title - should produce error, minimizing component should show error bar on the side
- [ ] Menu group tests
  - [ ] Add section should work
  - [ ] drag and drop (2nd level should work), try this multiple times to make sure the right component can be consistently selected to drag
  - [ ] type in a very long string for title of subitem - should produce error, minimizing submenu should show error bar, minimizing entire menu group component should show error
  - [ ] Delete section should work

**Comment by seaerchin** [comment]
#1462 combined with gb ff tests in #1449

**Comment by seaerchin** [comment]
#1450 @harishv7 

- [ ] open hero section
- [ ] notification should not have `optional` tag after the form's label
- [ ] add `infobar` 
- [ ] infobar should not have `optional` tag after the form's label

**Comment by seaerchin** [comment]
#1439 @seaerchin 
- [ ] Navigate to homepage
  - [ ]  Preview should remain at hero and not scroll down

@alexanderleegs  pls help add thx

**Comment by seaerchin** [comment]
#1461 @harishv7 

- [ ] Go to edithomepage for any private repo (e.g. a-test-v4)
- [ ] Verify that images show up on 
  - [ ] Hero banner
  - [ ] Left infopic
  - [ ] Right infopic
- [ ] Verify that nested images work as well (e.g. `/images/album/nested.jpg`)
- [ ] When creating a new infopic section, no error toast should appear

**Review by harishv7 — APPROVED** [review]

**Pull request merged**
