### PR TITLE
fix: adds multiple header buttons to increase and decrease size of header text

### PR DESCRIPTION
**Pull request by gweiying**
Addresses #320 with addition of new header button to allow users to increase and decrease the size of header text.

Screenshot 2020-12-30 at 12 04 52 PM

Note the initial click to create a large/small header is not very intuitive as clicking on the "large" header creates the smallest header that will increase in size as the user clicks it. Personally, I think this may not be so problematic as the contrast in the two buttons may encourage users to experiment, but please feedback if you have other ideas on the behavior!

### CODE REVIEW

**Review by alexanderleegs — COMMENTED** [review]
lgtm, but let's check with the designers whether this sufficiently solves the issue. @NatMaeTan do you have any feedback for this?

**Comment by seaerchin** [comment]
tagging @NatMaeTan and @prestonlimlianjie  - is this still relevant?

**Comment by NatMaeTan** [comment]
> tagging @NatMaeTan and @prestonlimlianjie - is this still relevant?

Think we would rethink the UI of it to be more like a dropdown, but the problem is still relevant. Not really a priority now tho, maybe when we do templates

**Comment by seaerchin** [comment]
@NatMaeTan at present, we can decrease the header size by continually clicking the `H` button until it hits the normal text size (then it goes back to the biggest one again); is this good enough for now? (so that i can close this PR HAHA)

**Comment by NatMaeTan** [comment]
Yea sure but we def need to come back to this!!

**Comment by seaerchin** [comment]
Closed for now!

**Pull request closed without merging**
