### PR TITLE
Fix/misc ui fixes

### PR DESCRIPTION
**Pull request by alexanderleegs**
This PR fixes a few existing UI issues.
- The settings modal width has been fixed to prevent it from changing
- The positions of the save and delete buttons have been swapped
- Users are redirected to the Workspace/Resources page if the subcategory folder they are in has no items
- Additional info has been provided for the files and images tabs
- An additional note has been added to the notification bar field so users know to leave it blank if they do not want a notification bar
- The minimum requirement for homepage fields has been removed, to resolve https://github.com/isomerpages/isomercms-frontend/issues/222
- The bug where the media modal would not appear if there were no images/files has been fixed
- The title of the media modal has been updated, which resolves https://github.com/isomerpages/isomercms-frontend/issues/221

### CODE REVIEW

**Review by gweiying — APPROVED** [review]
lgtm

**Review by kwajiehao — CHANGES_REQUESTED** [review]
A few comments:
- Save and delete buttons weren't swapped in `EditPage` layout
- Media cards are not aligned with info message and title - refer to Workspace as a reference
- Note on the site notification field in `EditHomepage` is a little too close to the text input, can we have a bit more space in between them?

**Comment by alexanderleegs** [comment]
> * Save and delete buttons weren't swapped in `EditPage` layout

Resolved in https://github.com/isomerpages/isomercms-frontend/pull/223/commits/06bd7cbb2551e77bcda1378b2340abd2bf3c8885

> * Media cards are not aligned with info message and title - refer to Workspace as a reference

Resolved in https://github.com/isomerpages/isomercms-frontend/pull/223/commits/ade6b4b4e18d30e12d6a55a052aef8d0f901658b

**Review by kwajiehao — APPROVED** [review]
lgtm

**Pull request merged**
