### PR TITLE
[DO NOT MERGE] Trigger e2e tests to test backend

### PR DESCRIPTION
**Pull request by dcshzj**
PR for testing [PR 903 on backend](https://redirect.github.com/isomerpages/isomercms-backend/pull/903). **DO NOT MERGE!**

### CODE REVIEW

**Comment by dcshzj** [comment]
!run e2e

**Comment by dcshzj** [comment]
!run e2e

**Comment by harishv7** [comment]
!run e2e

**Comment by dcshzj** [comment]
!run e2e

**Comment by kishore03109** [comment]
@dcshzj can we close this?

**Comment by dcshzj** [comment]
Oh yeah this can be closed now.

**Pull request closed without merging**
