### PR TITLE
fix(chromatic): attempt to get full commit hist

### PR DESCRIPTION
**Pull request by kishore03109**
## Problem

#1406 did not fully fix chromatic. We get this error during the comment based dev. 
Screenshot 2023-08-11 at 3 17 04 PM

## Solution

Trying out the solution [here](https://github.com/actions/checkout/issues/331#issuecomment-925405415) instead.  (Testing is a pain cuz I can only test this when it goes into dev)

### CODE REVIEW

**Review by dcshzj — DISMISSED** [review]

**Comment by kishore03109** [comment]
@dcshzj my friday brain reverted to the original solution that we knew already does not work. Using sol [here](https://github.com/actions/checkout/issues/331#issuecomment-925405415)

**Comment by dcshzj** [comment]
Wait do we still need to use `actions/checkout` to checkout the repository first?

**Comment by kishore03109** [comment]
@dcshzj 
> Wait do we still need to use actions/checkout to checkout the repository first?

Uhm wait ah isnt we checkout pr = already checked out repo?

**Comment by dcshzj** [comment]
> Uhm wait ah isnt we checkout pr = already checked out repo?

Hmm I'm not sure if the `hub` CLI will clone the repository first if it does not already exist in the workspace. But I think without the checkout, `hub` might not be aware which repository it is supposed to check out the PR for.

**Comment by kishore03109** [comment]
> Hmm I'm not sure if the hub CLI will clone the repository first if it does not already exist in the workspace. But I think without the checkout, hub might not be aware which repository it is supposed to check out the PR for.

be499ba55fccae9e5257f32757eb600194cef59a ok i add in actions/checkouts actions hopefully this the last pr I raise about this :sadge:

**Review by dcshzj — APPROVED** [review]

**Comment by kishore03109** [comment]
@dcshzj omg sorry I thought this was not approved yet :/

**Pull request merged**
