### PR TITLE
0.46.0

### PR DESCRIPTION
**Pull request by kishore03109**
- fix(announemnt): fix announcemnt bug [`#1532`](https://github.com/isomerpages/isomercms-frontend/pull/1532)
- Feat/text cards panel [`#1505`](https://github.com/isomerpages/isomercms-frontend/pull/1505)
- Fix/homepageAnnouncementScroll [`#1530`](https://github.com/isomerpages/isomercms-frontend/pull/1530)
- Feat/homepageAnnouncement [`#1502`](https://github.com/isomerpages/isomercms-frontend/pull/1502)
- fix(image): change image used [`#1531`](https://github.com/isomerpages/isomercms-frontend/pull/1531)
- chore(announcements): sync changes from template [`#1518`](https://github.com/isomerpages/isomercms-frontend/pull/1518)
- feat(feature tour): FF for hero [`#1508`](https://github.com/isomerpages/isomercms-frontend/pull/1508)
- refactor(hero): chnage to use breakpoints [`#1524`](https://github.com/isomerpages/isomercms-frontend/pull/1524)
- refactor(styles): shift to theme [`#1523`](https://github.com/isomerpages/isomercms-frontend/pull/1523)
- feat(announcements): add help overlay [`#1521`](https://github.com/isomerpages/isomercms-frontend/pull/1521)
- release(0.45.0): merge to develop [`#1519`](https://github.com/isomerpages/isomercms-frontend/pull/1519)

### CODE REVIEW

**Comment by kishore03109** [comment]
Tests for https://github.com/isomerpages/isomercms-frontend/pull/1532
https://github.com/isomerpages/isomercms-frontend/assets/42832651/7ba4eb3e-8ef3-4271-b990-1e9a8f1f2668
- [ ] CRUD operations on announcemnts (eg like the video above)

**Comment by kishore03109** [comment]
Tests for https://github.com/isomerpages/isomercms-frontend/pull/1505
https://github.com/isomerpages/isomercms-frontend/assets/22111124/2a1859ba-9350-4b5f-904a-663e8a504bd3

### Tests

- [ ] Go into edit homepage
- [ ] Click on add new section -> text cards
- [ ] New text card section should be editable
- [ ] Errors should cause section to have error bar when minimized
- [ ] Should be able to add a new card to this section
- [ ] Should have a maximum of 4 cards in this section, after which add card button becomes disabled
- [ ] Cards should be draggable
- [ ] Errors in card section show up when card is minimized, and also when section is minimized
- [ ] Errors should block saving
- [ ] On save, changes should persist after refresh

**Comment by kishore03109** [comment]
Tests for https://github.com/isomerpages/isomercms-frontend/pull/1530
## Tests 
- [ ] When modifying announcements, the screen should scroll to the particular announcement that is being modified

**Comment by kishore03109** [comment]
Tests for https://github.com/isomerpages/isomercms-frontend/pull/1502
## Tests

- [ ] Added in storybooks 
- [ ] login and you should see the new announcement (clear local storage / go incognito mode if you dont see it)

**Comment by kishore03109** [comment]
Tests for https://github.com/isomerpages/isomercms-frontend/pull/1518
## Tests

- [ ] Navigate to any site with the announcements component
- [ ] Ensure that there are no visible changes on the homepage preview
- [ ] Ensure that on very small viewports (<= 425px), the announcements component title remains centred

**Comment by kishore03109** [comment]
Tests for https://github.com/isomerpages/isomercms-frontend/pull/1508

- [ ] Ensure that you are a whitelisted site 
- [ ] Login enter in to the `/homepage` site. 
- [ ] Ensure that when you expand the hero section, feature tour pops up

**Comment by kishore03109** [comment]
Tests for https://github.com/isomerpages/isomercms-frontend/pull/1524 + https://github.com/isomerpages/isomercms-frontend/pull/1523
## Tests 
- [ ] go to homepage
- [ ] add any component that requires padding etc from tailwind (used hero banner here) 
- [ ] the padding should exist

**Comment by kishore03109** [comment]
Tests for https://github.com/isomerpages/isomercms-frontend/pull/1521

- [ ] Visit any site that can create a new announcements block
- [ ] Verify that the help overlay appears when hovering over the announcements block when adding a new section

**Review by dcshzj — APPROVED** [review]

**Pull request merged**
